# Generated by Django 4.0.3 on 2022-04-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='attachment',
        ),
    ]
