# Generated by Django 4.0.4 on 2022-04-14 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_projects', '0004_alter_priority_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'verbose_name_plural': '5. Bugs'},
        ),
        migrations.AlterModelOptions(
            name='buglog',
            options={'verbose_name_plural': '6. Bugs Log'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': '2. Priorities'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '1. Projects'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': '4. Status'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': '3. Bug Types'},
        ),
        migrations.AddField(
            model_name='project',
            name='assign',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
