# Generated by Django 4.0.4 on 2022-04-14 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_projects', '0005_alter_bug_options_alter_buglog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'verbose_name_plural': '6. Bugs'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': '3. Bug Priorities'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': '5. Bug Status'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': '4. Bug Types'},
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_module', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assign_module_user', models.ManyToManyField(related_name='module_user', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. Project Modules',
            },
        ),
    ]
