# Generated by Django 4.0.4 on 2022-04-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_projects', '0006_alter_bug_options_alter_priority_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodule',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='apps_projects.project'),
            preserve_default=False,
        ),
    ]
