# Generated by Django 4.0.4 on 2022-04-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_projects', '0007_projectmodule_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectmodule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectmodule',
            name='updated_at',
        ),
    ]
