# Generated by Django 4.0.4 on 2022-04-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_projects', '0009_remove_projectmodule_assign_module_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='assign_module_user',
            field=models.CharField(choices=[], max_length=6),
        ),
    ]
