# Generated by Django 4.0.4 on 2022-04-14 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_projects', '0010_alter_projectmodule_assign_module_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodule',
            name='assign_module_user',
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='assign_module_user',
            field=models.ManyToManyField(related_name='assign', to=settings.AUTH_USER_MODEL),
        ),
    ]
