# Generated by Django 4.0.4 on 2022-04-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_projects', '0012_bug_project_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='project_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps_projects.projectmodule'),
        ),
    ]
