# Generated by Django 4.0.4 on 2022-04-18 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps_projects', '0013_alter_bug_project_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='assign_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_module_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
