# Generated by Django 4.0.3 on 2022-04-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesment',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
