# Generated by Django 4.0.3 on 2022-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_home', '0002_alter_assesment_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candiadate_name', models.CharField(max_length=100)),
                ('candiadate_email', models.EmailField(max_length=254)),
                ('candiadate_mobile', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candiadate_id', models.CharField(max_length=100)),
                ('token', models.TextField()),
                ('assessment_id', models.IntegerField(blank=True, null=True)),
                ('process', models.IntegerField(default=0)),
            ],
        ),
    ]
